import { AI_TRAINING_CRAWLERS } from './jurisdictions/vendors.js'
import type { ConsentConfig } from './types.js'

/**
 * Map our internal vendor identifiers to the User-Agent strings each AI
 * crawler advertises. Used by `generateAiBotRobotsRules`. Keep this in sync
 * with `AI_TRAINING_CRAWLERS` in jurisdictions/vendors.ts.
 */
const VENDOR_TO_USER_AGENT: Record<string, string> = {
  gptbot: 'GPTBot',
  claudebot: 'ClaudeBot',
  'anthropic-ai': 'anthropic-ai',
  'google-extended': 'Google-Extended',
  perplexitybot: 'PerplexityBot',
  ccbot: 'CCBot',
  bytespider: 'Bytespider',
  'applebot-extended': 'Applebot-Extended',
  'meta-externalagent': 'meta-externalagent',
  'oai-searchbot': 'OAI-SearchBot',
}

export type AiTxtOptions = {
  /** Site URL — included as a comment for human readers and crawlers. */
  siteUrl?: string
}

/**
 * Whether the site's effective stance is to deny AI training. True when:
 *  - The config has no `ai_training` category at all (safer default)
 *  - Or `ai_training.default !== true`
 *
 * Granting AI training requires an explicit `default: true` opt-in.
 */
function isAiTrainingDenied(config: ConsentConfig): boolean {
  const cat = config.categories.ai_training
  if (!cat) return true
  if (cat.required) return false
  return cat.default !== true
}

/**
 * Generate the contents of `/ai.txt` (Spawning.ai-compatible format).
 *
 * Returns a robots.txt-style plain-text file declaring the site's AI
 * training policy based on the `ai_training` category. If the category
 * isn't declared, defaults to disallow — the safer position under the
 * EU AI Act Article 53 framework where machine-readable opt-outs are
 * legally enforceable from August 2026.
 *
 * @example
 * ```ts
 * generateAiTxt(config, { siteUrl: 'https://example.com' })
 * // → "# https://example.com/ai.txt
 * //    # Generated by Tickbox from consent.config.ts
 * //    # Policy version: 2026-05-06
 * //
 * //    User-Agent: *
 * //    Disallow: /
 * //    "
 * ```
 */
export function generateAiTxt(config: ConsentConfig, options: AiTxtOptions = {}): string {
  const denied = isAiTrainingDenied(config)
  const lines: string[] = []
  if (options.siteUrl) {
    const trimmed = options.siteUrl.replace(/\/+$/, '')
    lines.push(`# ${trimmed}/ai.txt`)
  }
  lines.push('# Generated by Tickbox from consent.config.ts')
  if (config.policy?.version) {
    lines.push(`# Policy version: ${config.policy.version}`)
  }
  lines.push('')
  lines.push('User-Agent: *')
  lines.push(denied ? 'Disallow: /' : 'Allow: /')
  return `${lines.join('\n')}\n`
}

/**
 * Generate a robots.txt fragment with Disallow rules for AI training
 * crawlers based on the `ai_training` category in the config.
 *
 * If `ai_training.vendors` is non-empty, only those crawlers are listed.
 * If absent or empty, all crawlers in `AI_TRAINING_CRAWLERS` are listed.
 * If AI training is allowed, returns a single comment line so the caller
 * can still concatenate it into their robots.txt without conditional logic.
 *
 * Append this to your existing robots.txt content.
 *
 * @example
 * ```ts
 * const robotsTxt = `${userExistingRobotsRules}\n\n${generateAiBotRobotsRules(config)}`
 * ```
 */
export function generateAiBotRobotsRules(config: ConsentConfig): string {
  const denied = isAiTrainingDenied(config)
  if (!denied) {
    return '# AI training: allowed for all crawlers\n'
  }

  const cat = config.categories.ai_training
  const declaredVendors = cat?.vendors ?? []
  const vendorList =
    declaredVendors.length > 0 ? declaredVendors : (AI_TRAINING_CRAWLERS as readonly string[])

  const userAgents = vendorList
    .map((v) => VENDOR_TO_USER_AGENT[v])
    .filter((ua): ua is string => Boolean(ua))

  if (userAgents.length === 0) {
    return '# AI training: denied (no known crawlers in config)\n'
  }

  const sections = userAgents.map((ua) => `User-agent: ${ua}\nDisallow: /\n`)
  return `# AI training crawlers — blocked\n${sections.join('\n')}`
}
