import { type ConsentConfig, ConsentStore, applyConsent } from '@tickboxhq/core'
import { ConsentStoreKey } from '@tickboxhq/vue'
import { defineNuxtPlugin, useRequestHeaders } from 'nuxt/app'
// @ts-expect-error virtual template generated by the module at build time
import userConfig from '#build/tickbox-config'

export default defineNuxtPlugin({
  name: 'tickbox',
  enforce: 'pre',
  setup(nuxtApp) {
    const config =
      (userConfig as { default?: ConsentConfig } & ConsentConfig)?.default ??
      (userConfig as ConsentConfig)

    if (!config || typeof config !== 'object' || !('jurisdiction' in config)) {
      console.error(
        '[@tickboxhq/nuxt] Could not load consent config from `#tickbox-config`. ' +
          'Make sure your `consent.config.ts` default-exports a value created via `defineConsent()`.',
      )
      return
    }

    if (config.jurisdiction === 'auto') {
      console.warn(
        '[@tickboxhq/nuxt] `jurisdiction: "auto"` is not yet supported by the Nuxt module. ' +
          'Set an explicit jurisdiction in your consent config for now.',
      )
      return
    }

    const store = new ConsentStore(config, {
      jurisdiction: config.jurisdiction,
      storage: config.storage,
      applyEffects: true,
      onApply: import.meta.client
        ? (state) => applyConsent(state, { consentMode: config.consentMode })
        : undefined,
    })

    if (import.meta.server) {
      const headers = useRequestHeaders(['cookie'])
      store.hydrateFromHeader(headers.cookie)
    }

    if (import.meta.client) {
      nuxtApp.hook('app:mounted', () => {
        store.hydrate()
      })
    }

    nuxtApp.vueApp.provide(ConsentStoreKey, store)
  },
})
